{{- if .Values.redis.pwd  }}
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.redis.pwd }}
{{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis
        image: redislabs/redismod
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        {{- if .Values.redis.pwd  }}          
        args: ["--requirepass", {{ .Values.redis.pwd }}]
        {{- end }}
        env:
        - name: MASTER
          value: "true"
        {{- if .Values.redis.pwd  }}  
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PASS
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: redis-pod
  ports:
  - protocol: TCP
    port: {{ .Values.redis.port }}
    targetPort: 6379
---
{{- if .Values.redis.loadbalancer  }}
apiVersion: v1
kind: Service
metadata:
  name: redis-loadbalancer-srv
  namespace: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: {{ .Values.redis.port }}
  selector:
    app: redis-pod
  type: LoadBalancer
{{- end}}