apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakes-server-dpt
  namespace: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snakes-server-pod
  template:
    metadata:
      labels:
        app: snakes-server-pod
    spec:
      containers:
      - name: server
        image: {{ .Values.registry }}/snakes-server:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        env:
        - name: REDIS_URI
          value: {{ .Values.redis.serviceName }}:{{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: snakes-server-clusterip-srv
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: snakes-server-pod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snakes-server-ingress-srv
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: snakes-server

    # used to rewrite paths to server so they don't contain snakes prefix
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /snakes(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: snakes-server-clusterip-srv
            port:
              name: http